### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Russe098** [imjyotiraditya/Echoir#13]
I hope you will add Bangladesh country as region, please accept my request, wish you good health stay well dear 

There is also a request to add one more country, country name India

**Comment by imjyotiraditya** [comment]
Thank you for your request.

I'd like to clarify how our region settings work. The supported regions list doesn't limit where the app can be used - for example, if a song is from Japan but LADIT doesn't support Japan as a region, you can still access Japanese songs. Similarly, Bengali songs are available regardless of whether Bangladesh is listed as a region.

The region selector is specifically for checking track availability and versions across LADIT-supported countries. For example, a song like 'Timeless' might be available in some regions but not others, or some regions might have the explicit version while others have the clean version. The selector helps you check these differences. Therefore, you don't need your specific country to be listed in the options to access content.
