### ISSUE TITLE
DLs always stuck in queue.

### ISSUE THREAD

**Issue by San-sec** [imjyotiraditya/Echoir#23]
Downloads sometimes failed or tracks that get stuck in the queue while downloading albums.  

It would be great if you could add a feature which could retry downloadign to help resolve these issues.

![Screenshot_20241212-184543_Echoir](https://github.com/user-attachments/assets/7372f577-7542-4c31-8322-41dcee36a021)

**Comment by imjyotiraditya** [comment]
i have fixed this in a recent commit. and planning for a release.

**Comment by imjyotiraditya** [comment]
@San-sec can you check if you are facing any issues in the new release?

**Comment by San-sec** [comment]
The new release has been running smoothly without any issues so far.
